sonar.projectKey=Andersonfrfilho_react-native-template 
sonar.projectName=react-native-template
sonar.organization=andersonfrfilho
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,android/**,ios/**,src/**/*.test.js,src/**/*.spec.js,src/**/*.test.jsx,src/**/*.spec.jsx
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
# Optional: For test coverage

sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js
# Test coverage report path (e.g., from Jest's LCOV output)
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml