name: e2e-android

on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v4

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: 'x64'

      - name: Setup Android Emulator
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

          echo "y" | sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;arm64-v8a"

          echo "no" | avdmanager create avd --force \
            --name Pixel_8_API_35_1 \
            --device "pixel" \
            --package "system-images;android-30;google_apis;arm64-v8a" \
            --tag "google_apis" \
            --abi "arm64-v8a"

          emulator -list-avds

      - name: Install node_modules
        run: |
          npm install

      - name: Start RN Packager
        run: |
          npx react-native start &

      - name: Build detox
        run: |
          npx detox build -c android.emulator.release

      - name: Android Run Detox
        run: |
          npx detox test --configuration android.emulator.release --cleanup --headless --record-logs all

      - name: Upload Test Artifact - GitHub Action
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
