name: e2e-android
on: push
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Node
        uses: actions/setup-node@v4

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          architecture: 'x64'

      - name: Download and Create Android Emulator Image
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
          $ANDROID_HOME/tools/bin/avdmanager create avd --force -n TestEmulator -d pixel --package 'system-images;android-29;google_apis;x86'
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Install node_modules
        run: |
          npm install

      - name: Start RN Packager
        run: |
          npx react-native start &

      - name: Build detox
        run: |
          npx detox build -c android.emulator.release

      - name: Android Run Detox
        run: |
          npx detox test --configuration android.emulator.release  --cleanup --headless --record-logs all

      - name: Upload Test Artifact - GitHub Action
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts
